started work on abstraction layer, wrapped original implementaton
rihp/autogpt-helloworld-plugin pull request #4
Opened 2023-05-13 14:21 UTC by ppetermann

## DRAFT

## Description
This PR bundles the work to abstract the implementations in the planner, which is supposed to allow other/more complex 
storage implementations (for example sqliite)

2023-05-14 07:33 UTC, rihp requested changes

2023-05-14 07:33 UTC, rihp commented on src/auto_gpt_planner_plugin/planner_protocol.py
> +            task (PlannerTask): The task id to be completed.
is the id passed or is it an entire PlannerTask object ?

2023-05-14 07:33 UTC, rihp commented on src/auto_gpt_planner_plugin/planner_protocol.py
> +    def complete_task(self, task: PlannerTask, name: str = "PlannerGPT"):
Why do we need to pass name arg ?

2023-05-14 07:33 UTC, rihp commented on src/auto_gpt_planner_plugin/planner_protocol.py
> +class PlannerProtocol(Protocol):
can we give a docstring with overview general description of what this class is doing ?

2023-05-14 07:33 UTC, rihp commented on src/auto_gpt_planner_plugin/__init__.py
> +            get_current_task
is this the right function to call ?

2023-05-14 18:24 UTC, ppetermann commented on src/auto_gpt_planner_plugin/planner_protocol.py
> +            task (PlannerTask): The task id to be completed.
yeh, haven't fixed the comment yet, as mentioned this is still draft

2023-05-14 18:26 UTC, ppetermann commented on src/auto_gpt_planner_plugin/planner_protocol.py
> +    def complete_task(self, task: PlannerTask, name: str = "PlannerGPT"):
essentally this allows a storage implementation to keep multiple instances apart (thats once the name is actually injected, which it isn't yet)

2023-05-14 18:27 UTC, ppetermann commented on src/auto_gpt_planner_plugin/planner_protocol.py
> +class PlannerProtocol(Protocol):
as mentioned before, this is draft, doc strings aren't final  at all

2023-05-14 18:29 UTC, ppetermann commented on src/auto_gpt_planner_plugin/__init__.py
> +            get_current_task
yes, get next task is aliasing get_current_task, just so it is less likely to stumble over making the distinction

2023-05-24 20:28 UTC, ppetermann commented on src/auto_gpt_planner_plugin/__init__.py
> +            implementation_name="SqlitePlanner"  # TODO: make this configurable
should make this configureable before merge

2025-06-06 12:48 UTC, closed without merging